version: '5.0'

actions:

  diabetes_prev:
    run: ehrql:v1 generate-measures analysis/diabetes_measures.py --output output/tables/annual_counts/diabetes/:csv
    outputs:
      moderately_sensitive:
        csv: output/tables/annual_counts/diabetes/*.csv 